import { StyleSheet, Dimensions } from "react-native";
export const styles = StyleSheet.create({
  lottie: {
    height: 100,
    width: 100,
  },
  searchBox: {
    width: "90%",
    height: 50,
    display: "flex",
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    justifyContent: "space-between",
  },
  searchBar: {
    backgroundColor: "#FFFFFF33",
    borderRadius: 30,
    paddingLeft: 20,
    height: "100%",
    flex: 1,
    fontSize: 18,
    color: "#fff",
  },
  searchBarClose: {
    maxWidth: 0,
  },
  searchBtn: {
    padding: 2,
    height: 50,
    width: 50,
    backgroundColor: "#FFFFFF4D",
    borderRadius: 999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  searchBtnOnly: {
    margin: "auto",
  },
  heading: {
    color: "#fff",
    fontSize: 25,
    fontWeight: "600",
    textAlign: "right",
  },
  imgBackground: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 25,
    gap: 30,
    position: "absolute",
    left: 0,
    top: 0,
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
    zIndex: -10,
  },
  weatherBox: {
    height: 140,
    width: 110,
    backgroundColor: "#FFFFFF22",
    borderRadius: 20,
    paddingTop: 15,
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginRight: 20,
  },
  nameHeadingView: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 15,
    flexWrap: "wrap",
    width: "90%",
  },
});
